---
title: "heart_female"
output: html_document
date: "2023-09-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load libraries
```{r}
library(plyr)
library(reshape2)
library(dplyr)
library(stringr)
library(readxl)
library(readr)
library(magrittr)
library(ggplot2)

# set project directory
projectDir <- "/Users/taylaalbertini/Desktop/R studio/count_preprocessing"
ERR2704717 <- file.path(projectDir, "rawData/heart_female/ERR2704717.tab")
ERR10763248 <- file.path(projectDir, "rawData/heart_female/ERR10763248.tab")
SRR3192434 <- file.path(projectDir, "rawData/heart_female/SRR3192434.tab")
SRR9887706 <- file.path(projectDir, "rawData/heart_female/SRR9887706.tab")
SRR9887711 <- file.path(projectDir, "rawData/heart_female/SRR9887711.tab")

tissue <- "heart"
sex <- "female"
```

# import rawCounts
```{r}
# import the counts table
## ERR2704717
ERR2704717 <- read_delim(file = ERR2704717,
                        col_names = FALSE,
                        delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensemble=X1,ERR2704717=X2)

## ERR10763248
ERR10763248 <- read_delim(file = ERR10763248,
                          col_names = FALSE,
                          delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensemble=X1,ERR10763248=X2)

## SRR3192434
SRR3192434  <- read_delim(file = SRR3192434,
                        col_names = FALSE,
                        delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensemble=X1,SRR3192434=X2)

## SRR9887706 
SRR9887706 <- read_delim(file = SRR9887706,
                        col_names = FALSE,
                        delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensemble=X1,SRR9887706=X2)

## SRR9887711
SRR9887711 <- read_delim(file = SRR9887711,
                        col_names = FALSE,
                        delim = "\t") %>%
  as.data.frame() %>%
  dplyr::select(ensemble=X1,SRR9887711=X2)
```

# stitching the samples together
```{r}
#merging columns
mergedCounts_heartFemale <- dplyr::left_join(ERR2704717,ERR10763248, by="ensemble") %>%
  dplyr::left_join(.,SRR3192434, by="ensemble") %>%
  dplyr::left_join(.,SRR9887706, by="ensemble") %>%
  dplyr::left_join(.,SRR9887711, by="ensemble")

#remove rows with all zeros
mergedCounts_heartFemale <- mergedCounts_heartFemale[rowSums(mergedCounts_heartFemale[,-1])>0,]
rownames(mergedCounts_heartFemale) <- NULL
```

# remove the number after the period
```{r}
mergedCounts_heartFemale %<>% tidyr::separate(., col = ensemble, into = c("ensemble", "right")) %>%
  dplyr::select(., -right) %>%
  tibble::column_to_rownames("ensemble")
```

# library size scatter plot 
```{r}
# make a small data frame with information needed for the plot
plotData_heartFemale <- mergedCounts_heartFemale %>%
  colSums(.) %>%
  as.data.frame() %>%
  tibble::rownames_to_column() %>%
  set_colnames(c("sample", "totalCounts")) %>%
  arrange(., totalCounts)

# make the plot
ggplot(data = plotData_heartFemale,
       aes(x=reorder(sample, totalCounts),
           y=totalCounts,
           colour=totalCounts<9000000)) +

  geom_point(size=5) +
  scale_colour_manual(name='Read count\nthreshold',
                      values=setNames(c('red','green'),
                                      c(TRUE, FALSE))) +

  geom_hline(yintercept=9000000,
             show.legend=FALSE,
             linetype="dotted",
             colour="red") +


  ggtitle("Raw counts heart female - all samples\n(hg38)") +
  theme_bw(base_size=16) +
  labs(title="Library size",
       subtitle="Raw mRNA read counts in heart female",
       x="Sample name",
       y="mRNA read counts") +
  
  theme(axis.text.x=element_text(angle=270,
                                 hjust=1.5,
                                 colour="black",
                                 size=12),

        axis.text.y = element_text(angle=0,
                                   colour="black",
                                   size=14))
```

# output file
```{r}
write.csv(mergedCounts_heartFemale, file = file.path(projectDir, "rawData/combinedRaw/rawCounts_heartFemale.csv"))
```





